FIND_LIBRARY(EXACTCOLORS_LIBRARY NAMES exactcolor libexactcolor HINTS ${EXACTCOLORS_ROOT_DIR} ${EXACTCOLORS_ROOT_DIR}/lib)
FIND_LIBRARY(SEWELL_LIBRARY NAMES sewell libsewell HINTS ${EXACTCOLORS_ROOT_DIR} ${EXACTCOLORS_ROOT_DIR}/lib)
FIND_PATH(EXACTCOLORS_INCLUDE_DIR exactcolors/color.h HINTS ${EXACTCOLORS_ROOT_DIR} ${EXACTCOLORS_ROOT_DIR}/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EXACTCOLORS DEFAULT_MSG
  EXACTCOLORS_INCLUDE_DIR EXACTCOLORS_LIBRARY SEWELL_LIBRARY)

IF(EXACTCOLORS_FOUND)
  MARK_AS_ADVANCED(EXACTCOLORS_INCLUDE_DIR EXACTCOLORS_LIBRARY SEWELL_LIBRARY)
  SET(EXACTCOLORS_INCLUDE_DIRS ${EXACTCOLORS_INCLUDE_DIR})
  SET(EXACTCOLORS_LIBRARIES ${EXACTCOLOR_LIBRARY} ${SEWELL_LIBRARY})
ENDIF()